Add rhythm indicators on Controller
jamilfaisal/Meow-Tunes pull request #67
Opened 2022-11-14 05:27 UTC by judy-n

- Made a fix so the "Purr-fect", "Nice", "Oops" text shows on controller

2022-11-14 06:00 UTC, jamilfaisal requested changes
Works on both my xbox and switch controllers. Nice work! Will approve after my two comments are addressed

2022-11-14 06:00 UTC, jamilfaisal commented on Assets/Scripts/PlayerScripts/PlayerAction.cs
> +using Unity.VisualScripting;
I don't think this import is needed

2022-11-14 06:00 UTC, jamilfaisal commented on Assets/Scripts/PlayerScripts/PlayerAction.cs
> +                    if (Math.Abs(_audioTime - (_timeStamp)) < _marginOfError)
I think lines 108 - 119 are the same as lines 58 - 68. If that's the case, can you please refactor these lines into one function and call in both places

2022-11-14 06:23 UTC, judy-n commented on Assets/Scripts/PlayerScripts/PlayerAction.cs
> +using Unity.VisualScripting;
Fixed!

2022-11-14 06:24 UTC, judy-n commented on Assets/Scripts/PlayerScripts/PlayerAction.cs
> +                    if (Math.Abs(_audioTime - (_timeStamp)) < _marginOfError)
Fixed this

2022-11-14 06:29 UTC, jamilfaisal approved these changes

2022-11-15 04:06 UTC, lilvedaes approved these changes
LGTM c:

2022-11-15 04:16 UTC, merged